# Generated by Django 5.1.4 on 2025-01-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_blogpost_author_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='author_id',
        ),
    ]
